## 2.2 Pytorch Tensor

### 1. 텐서 만들기

In [ ]:
pip install torch torchvision

In [5]:
import torch
import numpy as np

np.set_printoptions(precision=3)
a = [1, 2, 3]
b = np.array([4,5,6], dtype=np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [6]:
t_ones = torch.ones(2,3)
print(t_ones.shape)
print(t_ones)

torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
rand_tensor = torch.rand(2,3)
print(rand_tensor)

tensor([[0.7208, 0.1066, 0.5463],
        [0.8746, 0.5615, 0.5078]])


### 2. 텐서 데이터 타입, 크기 조작

### 2-1. 데이터 타입 변경

In [8]:
t_a_new = t_a.to(torch.int64)
print(t_a_new.dtype)

torch.int64


### 2-2. 텐서 전치

In [9]:
t = torch.rand(3,5)
t_tr = torch.transpose(t, 0, 1)
print(t.shape, ' --> ', t_tr.shape)

torch.Size([3, 5])  -->  torch.Size([5, 3])


### 2.3. 텐서 크기 바꾸기 (에를 들어, 1d vector -> 2d vector)

In [10]:
t = torch.zeros(30)
t_reshape = t.reshape(5,6)
print(t_reshape.shape)

torch.Size([5, 6])


### 2.4. 불필요한 차원 삭제(예를 들어,가운데의 크기가 1인 차원은 불필요)

In [13]:
t = torch.zeros(1, 2, 1, 4, 1)
t_sqz = torch.squeeze(t, 2)
print(t.shape, '--->', t_sqz.shape)

torch.Size([1, 2, 1, 4, 1]) ---> torch.Size([1, 2, 4, 1])


### 3. 텐서에 수학 연산 적용

In [18]:
torch.manual_seed(1)
t1 = 2 * torch.rand(5,2) - 1 #[-1, 1] 사이의 균등 분포
t2 = torch.normal(mean=0, std = 1, size=(5,2)) #표준 정규 분포
print(t1)
print(t2)

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])
tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])


### 3.1. 텐서 곱셈

In [20]:

t3 = torch.multiply(t1, t2)
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


### 3.2. 평균

In [23]:
t4 = torch.mean(t1, axis=0)
print(t4)

tensor([-0.1373,  0.2028])


### 3.2 곱(matmul)

In [25]:
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))
print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


### 3.3. normalization

In [26]:
norm_t1 = torch.linalg.norm(t1, ord=2, dim=1)
print(norm_t1)

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])


### 3.3.1 numpy와 결과 비교

In [27]:
np.sqrt(np.sum(np.square(t1.numpy()), axis=1))

array([0.678, 0.508, 1.116, 0.549, 0.185], dtype=float32)

### 4. 텐서 나누기, 쌓기, 연결

### 4.1 같은 크기 분할

In [32]:
torch.manual_seed(1)
t = torch.rand(6)
print(t)

t_splits = torch.chunk(t,3)
print(t_splits)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])
(tensor([0.7576, 0.2793]), tensor([0.4031, 0.7347]), tensor([0.0293, 0.7999]))


### 4.2 다른 분할 크기

In [31]:
torch.manual_seed(1)
t = torch.rand(5)
print(t)

t_splits = torch.split(t, split_size_or_sections=[3,2])
print(t_splits)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])
(tensor([0.7576, 0.2793, 0.4031]), tensor([0.7347, 0.0293]))


### 4.3 텐서 연결

In [34]:
A = torch.ones(3)
B = torch.zeros(2)
print(A)
print(B)
C = torch.cat([A, B], axis=0)
print(C)

tensor([1., 1., 1.])
tensor([0., 0.])
tensor([1., 1., 1., 0., 0.])


### 4.4 텐서 쌓기

In [35]:
A = torch.ones(3)
B = torch.zeros(3)
S = torch.stack([A, B], axis = 1)
print(S)

tensor([[1., 0.],
        [1., 0.],
        [1., 0.]])
